version: 2

build:
  os: ubuntu-22.04
  tools:
    python: "miniconda3-4.7"
    rust: "1.70"
  jobs:
    post_install:
      - python -c "import pypsg; pypsg.settings.save_settings(api_key='$PSG_KEY')"

conda:
  environment: environment-rtd.yml

sphinx:
  configuration: docs/source/conf.py