build:
  os: ubuntu-22.04
  tools:
    python: "3.9"
  commands:
    - mkdir _readthedocs/
    - pwd
    - ls
    - wget --no-check-certificate "https://drive.google.com/uc?export=download&id=1UoiuQ1TYrT67PyuGI4ZiRij8JAxL2YQ4" -O _readthedocs/0.4.0.zip
    - ls _readthedocs/
    - unzip _readthedocs/0.4.0.zip -d _readthedocs/
    - ls _readthedocs/
    - ls _readthedocs/html/