build:
    os: ubuntu-22.04
    tools:
        python: "3.9"
    commands:
        - mkdir _readthedocs/
        - cd _readthedocs
        - mkdir html
        - cd html
        - fname="index.html"
        - touch $fname
        - echo "<!DOCTYPE html>" >> $fname
        - echo "<html lang="en">" >> $fname
        - echo "<head>" >> $fname
        - echo "<meta http-equiv=\"refresh\" content=\"0; url=https://vspec-collab.github.io/VSPEC/\" />" >> $fname
        - echo "</head>" >> $fname
        - echo "<body>" >> $fname
        - echo "</body>" >> $fname
        - echo "</html>" >> $fname
        - pwd
        - ls
        - cat $fname