build:
  os: ubuntu-22.04
  tools:
    python: "3.9"
  commands:
    - mkdir _readthedocs/
    - pwd
    - ls
    - wget --no-check-certificate "https://drive.google.com/uc?export=download&id=1PHvqcV3ofjdBO4XKUv9oQOH4gl_4ruNd" -O _readthedocs/0.5.0.zip
    - ls _readthedocs/
    - unzip _readthedocs/0.5.0.zip -d _readthedocs/
    - ls _readthedocs/
    - ls _readthedocs/html/