name: vspec

channels:
  - conda-forge
  - defaults


dependencies:
  - python=3.9
  - cartopy
  - pip
  - pip:
    - numpy
    - astropy
    - pandas
    - matplotlib
    - scipy
    - pathlib
    - tqdm
    - h5py
    - tinygp
    - jax
    - netCDF4
    - requests
    - git+https://github.com/tedjohnson12/xoflares.git@numpy-only
    - sphinxcontrib-napoleon
    - sphinx-automodapi
    - numpydoc
    - nbsphinx
    - nbsphinx-link
    - sphinxcontrib-bibtex
    - sphinx-gallery
    - furo
    - imageio