name: Package and Test

on:
  pull_request:
    branches:
      - main
      - develop
  workflow_dispatch:
  release:
    types: [published]

jobs:
  build-linux:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 5

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: '3.10'
    - name: Add conda to system path
      run: |
        # $CONDA is an environment variable pointing to the root of the miniconda directory
        echo $CONDA/bin >> $GITHUB_PATH
    - name: Install dependencies
      run: |
        conda env update --file environment.yml --name base
    - name: Lint with flake8
      run: |
        conda install flake8
        # stop the build if there are Python syntax errors or undefined names
        flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
        # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
        flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
    - name: Test and get coverage report
      env:
        COVERALLS_REPO_TOKEN: ${{ secrets.COVERALLS_REPO_TOKEN }}
        PSG_KEY: ${{ secrets.PSG_API_KEY }}
      run: |
        conda install pytest
        pip install pytest-timeout
        pip install coveralls
        python -c "import pypsg; pypsg.settings.save_settings(api_key='$PSG_KEY')"
        python -c "from pypsg.globes.waccm.waccm import download_test_data; download_test_data()"
        coverage run --source=VSPEC -m pytest --timeout=1000 --test1 test/end_to_end_tests/test1/test_test1.py test/pytest
        coveralls
